import math

WIDTH = 800
HEIGHT = 600
HALF_WIDTH = WIDTH // 2
HALF_HEIGHT = HEIGHT // 2
PENTA_HEIGHT = 5 * HEIGHT
DOUBLE_HEIGHT = 2 * HEIGHT
SCREEN_SIZE = (WIDTH, HEIGHT)
FPS_POS = (10, 10)
TILE = 64

# RAY CASTING SETTINGS
FOV = math.pi / 3
HALF_FOV = FOV / 2
NUM_RAYS = 200
MAX_DEPTH = 600
DELTA_ANGLE = FOV / NUM_RAYS
DIST = NUM_RAYS / (2 * math.tan(HALF_FOV))
PROJ_COEFF = 3 * DIST * TILE
SCALE = WIDTH // NUM_RAYS

# SPRITE SETTINGS
DOUBLE_PI = math.pi * 2
CENTER_RAY = NUM_RAYS // 2 - 1
FAKE_RAYS = 100
FAKE_RAYS_RANGE = NUM_RAYS - 1 + 2 * FAKE_RAYS

# TEXTURE SETTINGS (
TEXTURE_WIDTH = 128
TEXTURE_HEIGHT = 128
TEXTURE_SCALE = TEXTURE_WIDTH // TILE

# PLAYER START CONSTS
player_pos = (HALF_WIDTH, HALF_HEIGHT)
player_angle = 0
player_speed = 4
player_angle_speed = 0.04

# COLORS
WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
RED = (220, 0, 0)
GREEN = (0, 220, 0)
BLUE = (0, 0, 220)
SKY_BLUE = (51, 153, 255)
DARK_GREY = (50, 50, 50)
PURPLE = (120, 0, 120)